sudo: false

language: python

python: 2.7.9

sudo: false

branches:
  except:
    - master

cache: pip

script:
  - ./tests/all_tests.py

after_failure:
  - cat ./Logs/sickrage.log

notifications:
  irc: "irc.freenode.net#sickrage-builds"

  email:
    on_success: change
    on_failure: change
